// Ant Design 아이콘 중앙 관리
import React from 'react';
import {
  // 기본 아이콘들
  UserOutlined,
  LockOutlined,
  SearchOutlined,
  CloseOutlined,
  PlusOutlined,
  EditOutlined,
  DeleteOutlined,
  CalendarOutlined,
  ClockCircleOutlined,
  BarChartOutlined,
  MedicineBoxOutlined,
  TeamOutlined,
  DashboardOutlined,
  FileTextOutlined,
  ScheduleOutlined,
  PlusCircleOutlined,
  DownOutlined,
  SoundOutlined,
  ReloadOutlined,
  BellOutlined,
  AudioOutlined,
  BugOutlined,
  PhoneOutlined,
  PlayCircleOutlined,
  DownloadOutlined,
  PrinterOutlined,
  FilePdfOutlined,
  HomeOutlined,
  SettingOutlined,
  LogoutOutlined,
  MenuOutlined,
  NotificationOutlined,
  InfoCircleOutlined,
  CheckCircleOutlined,
  ExclamationCircleOutlined,
  WarningOutlined,
  StopOutlined,
  PauseCircleOutlined,
  LoadingOutlined,
  EyeOutlined,
  EyeInvisibleOutlined,
  HeartOutlined,
  StarOutlined,
  LikeOutlined,
  DislikeOutlined,
  MessageOutlined,
  MailOutlined,
  EnvironmentOutlined,
  GlobalOutlined,
  LinkOutlined,
  ShareAltOutlined,
  ExportOutlined,
  ImportOutlined,
  SaveOutlined,
  UndoOutlined,
  RedoOutlined,
  CopyOutlined,
  ScissorOutlined,
  FileOutlined,
  FolderOutlined,
  CloudUploadOutlined,
  CloudDownloadOutlined,
  SyncOutlined,
  RotateLeftOutlined,
  RotateRightOutlined,
  ZoomInOutlined,
  ZoomOutOutlined,
  FullscreenOutlined,
  FullscreenExitOutlined,
  ScanOutlined,
  QrcodeOutlined,
  BarcodeOutlined,
  CameraOutlined,
  VideoCameraOutlined,
  PictureOutlined,
  FileImageOutlined,
  FilePptOutlined,
  FileWordOutlined,
  FileExcelOutlined,
  FileZipOutlined,
  FileUnknownOutlined,
  FileMarkdownOutlined,
  FileJpgOutlined,
  FileAddOutlined,
  FileSearchOutlined,
  FileProtectOutlined,
  FileSyncOutlined,
  FileExclamationOutlined,
  FileDoneOutlined,
  FileGifOutlined,
  UserAddOutlined,
} from '@ant-design/icons';

// 메모이제이션된 아이콘 컴포넌트들
export const Icons = {
  // 기본 아이콘들
  User: React.memo(() => <UserOutlined />),
  Lock: React.memo(() => <LockOutlined />),
  Search: React.memo(() => <SearchOutlined />),
  Close: React.memo(() => <CloseOutlined />),
  Plus: React.memo(() => <PlusOutlined />),
  Edit: React.memo(() => <EditOutlined />),
  Delete: React.memo(() => <DeleteOutlined />),
  Calendar: React.memo(() => <CalendarOutlined />),
  Clock: React.memo(() => <ClockCircleOutlined />),
  Chart: React.memo(() => <BarChartOutlined />),
  Medicine: React.memo(() => <MedicineBoxOutlined />),
  Team: React.memo(() => <TeamOutlined />),
  Dashboard: React.memo(() => <DashboardOutlined />),
  FileText: React.memo(() => <FileTextOutlined />),
  Schedule: React.memo(() => <ScheduleOutlined />),
  PlusCircle: React.memo(() => <PlusCircleOutlined />),
  Down: React.memo(() => <DownOutlined />),
  Sound: React.memo(() => <SoundOutlined />),
  Reload: React.memo(() => <ReloadOutlined />),
  Bell: React.memo(() => <BellOutlined />),
  Audio: React.memo(() => <AudioOutlined />),
  Bug: React.memo(() => <BugOutlined />),
  Phone: React.memo(() => <PhoneOutlined />),
  Play: React.memo(() => <PlayCircleOutlined />),
  Download: React.memo(() => <DownloadOutlined />),
  Printer: React.memo(() => <PrinterOutlined />),
  FilePdf: React.memo(() => <FilePdfOutlined />),
  Home: React.memo(() => <HomeOutlined />),
  Setting: React.memo(() => <SettingOutlined />),
  Logout: React.memo(() => <LogoutOutlined />),
  Menu: React.memo(() => <MenuOutlined />),
  Notification: React.memo(() => <NotificationOutlined />),
  Info: React.memo(() => <InfoCircleOutlined />),
  Check: React.memo(() => <CheckCircleOutlined />),
  Exclamation: React.memo(() => <ExclamationCircleOutlined />),
  Warning: React.memo(() => <WarningOutlined />),
  Stop: React.memo(() => <StopOutlined />),
  Pause: React.memo(() => <PauseCircleOutlined />),
  Loading: React.memo(() => <LoadingOutlined />),
  Eye: React.memo(() => <EyeOutlined />),
  EyeInvisible: React.memo(() => <EyeInvisibleOutlined />),
  Heart: React.memo(() => <HeartOutlined />),
  Star: React.memo(() => <StarOutlined />),
  Like: React.memo(() => <LikeOutlined />),
  Dislike: React.memo(() => <DislikeOutlined />),
  Message: React.memo(() => <MessageOutlined />),
  Mail: React.memo(() => <MailOutlined />),
  Environment: React.memo(() => <EnvironmentOutlined />),
  Global: React.memo(() => <GlobalOutlined />),
  Link: React.memo(() => <LinkOutlined />),
  Share: React.memo(() => <ShareAltOutlined />),
  Export: React.memo(() => <ExportOutlined />),
  Import: React.memo(() => <ImportOutlined />),
  Save: React.memo(() => <SaveOutlined />),
  Undo: React.memo(() => <UndoOutlined />),
  Redo: React.memo(() => <RedoOutlined />),
  Copy: React.memo(() => <CopyOutlined />),
  Scissor: React.memo(() => <ScissorOutlined />),
  File: React.memo(() => <FileOutlined />),
  Folder: React.memo(() => <FolderOutlined />),
  CloudUpload: React.memo(() => <CloudUploadOutlined />),
  CloudDownload: React.memo(() => <CloudDownloadOutlined />),
  Sync: React.memo(() => <SyncOutlined />),
  RotateLeft: React.memo(() => <RotateLeftOutlined />),
  RotateRight: React.memo(() => <RotateRightOutlined />),
  ZoomIn: React.memo(() => <ZoomInOutlined />),
  ZoomOut: React.memo(() => <ZoomOutOutlined />),
  Fullscreen: React.memo(() => <FullscreenOutlined />),
  FullscreenExit: React.memo(() => <FullscreenExitOutlined />),
  Scan: React.memo(() => <ScanOutlined />),
  Qrcode: React.memo(() => <QrcodeOutlined />),
  Barcode: React.memo(() => <BarcodeOutlined />),
  Camera: React.memo(() => <CameraOutlined />),
  VideoCamera: React.memo(() => <VideoCameraOutlined />),
  Picture: React.memo(() => <PictureOutlined />),
  FileImage: React.memo(() => <FileImageOutlined />),
  FilePpt: React.memo(() => <FilePptOutlined />),
  FileWord: React.memo(() => <FileWordOutlined />),
  FileExcel: React.memo(() => <FileExcelOutlined />),
  FileZip: React.memo(() => <FileZipOutlined />),
  FileUnknown: React.memo(() => <FileUnknownOutlined />),
  FileMarkdown: React.memo(() => <FileMarkdownOutlined />),
  FileJpg: React.memo(() => <FileJpgOutlined />),
  FileAdd: React.memo(() => <FileAddOutlined />),
  FileSearch: React.memo(() => <FileSearchOutlined />),
  FileProtect: React.memo(() => <FileProtectOutlined />),
  FileSync: React.memo(() => <FileSyncOutlined />),
  FileExclamation: React.memo(() => <FileExclamationOutlined />),
  FileDone: React.memo(() => <FileDoneOutlined />),
  FileGif: React.memo(() => <FileGifOutlined />),
  UserAdd: React.memo(() => <UserAddOutlined />),
};

// 기본 export
export default Icons; 